# KADA Connect Backend - Render Deployment Configuration
# Deploy this Node.js/Express backend to Render with optimal settings

services:
  # Web Service Configuration
  - type: web
    name: kada-connect-backend
    runtime: node
    plan: free
    region: singapore

    # Build Configuration
    buildCommand: "npm install --production"
    startCommand: "npm start"

    # Health Checks
    healthCheckPath: /health
    healthCheckTimeout: 30
    autoDeploy: true

    # Environment Variables
    envVars:
      # Node Environment
      - key: NODE_ENV
        value: production

      # Server Configuration
      - key: PORT
        value: 10000  # Render's default port

      # CORS Configuration (set in Render dashboard)
      - key: ALLOWED_ORIGINS
        description: CORS allowed origins (comma-separated URLs)
        type: secret

    # Environment Variables (sensitive - set in Render dashboard)
    envVarGroups:
      - groupName: Supabase Config
        groupDescription: Supabase database connection settings
        vars:
          - key: SUPABASE_URL
            description: Supabase project URL
            type: secret
          - key: SUPABASE_SERVICE_KEY
            description: Supabase service role key
            type: secret

      - groupName: Google Drive API Config
        groupDescription: Google Drive API service account settings
        vars:
          - key: GOOGLE_PROJECT_ID
            description: Google Cloud project ID
            type: secret
          - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
            description: Google service account email
            type: secret
          - key: GOOGLE_PRIVATE_KEY
            description: Google service account private key
            type: secret

      - groupName: API Config
        groupDescription: API endpoints configuration
        vars:
          - key: API_BASE_URL
            description: API base URLs (comma-separated)
            type: secret

# Database Configuration (if using Render's PostgreSQL instead of Supabase)
# Uncomment and modify if needed
# databases:
#   - name: kada-connect-db
#     plan: free
#     region: oregon
#     databaseName: kada_connect
#     user: kada_user

# Deployment Hooks (optional)
# Uncomment to add custom deployment scripts
# deploymentHooks:
#   preBuild:
#     - command: "echo Starting build process..."
#   postBuild:
#     - command: "echo Build completed successfully!"

# Routing and Domains (optional)
# Uncomment for custom domains
# routes:
#   - type: redirect
#     source: www.your-domain.com
#     destination: https://your-domain.com